/**
 * ResolveAI demo seed dataset (ported from the PostgreSQL bootstrap).
 * Tuple: [title, description, catKey, subcat, prio, sev, sent, deptKey, status, needsReview, source, resolution]
 */
export const COMPLAINTS: string[][] = [
  ["Payment deducted but order not confirmed", "I was charged on my card but my order was never confirmed and there is no order ID in my account.", "payment", "Failed Transaction", "HIGH", "High", "Negative", "billing", "IN_PROGRESS", "false", "AI_GENERATED", "Verify the payment with the gateway, check whether the amount was captured, confirm or refund the order, and inform the customer."],
  ["Internet connection keeps disconnecting", "My internet connection has been disconnecting several times every evening for the past week, dropping my video calls.", "tech", "Internet Connectivity", "HIGH", "Medium", "Negative", "ts", "ASSIGNED", "false", "AI_GENERATED", "Check router logs and network stability, test the signal strength, then re-route the connection if needed."],
  ["Package has not arrived yet", "My order was dispatched 10 days ago but the tracking has not updated since. The package has not arrived.", "delivery", "Lost Shipment", "MEDIUM", "Medium", "Negative", "ops", "ESCALATED", "false", "AI_GENERATED", "Trace the shipment with the carrier, confirm the delivery address, and initiate a replacement or refund."],
  ["Unable to reset my account password", "I am unable to reset my password. The reset link expires immediately and I have tried several times.", "account", "Password Reset", "HIGH", "Medium", "Negative", "cs", "IN_PROGRESS", "false", "AI_GENERATED", "Confirm the registered email, regenerate a fresh reset token, and check email filtering rules."],
  ["Charged twice for the same transaction", "I noticed my account was charged twice for the same subscription payment this month.", "billing", "Duplicate Charge", "HIGH", "Medium", "Very Negative", "billing", "IN_PROGRESS", "false", "AI_GENERATED", "Compare both transaction IDs, reverse the duplicate charge, and confirm the refund to the customer."],
  ["Service was extremely slow today", "The entire application has been extremely slow all day. Every page takes over a minute to load.", "service", "Performance", "CRITICAL", "High", "Very Negative", "ts", "ESCALATED", "false", "AI_GENERATED", "Check server CPU and database load, scale resources, and review recent deployments for regressions."],
  ["Unauthorized login detected on my account", "I received an email about a login from a new device that I do not recognise. Someone may have accessed my account.", "security", "Unauthorized Access", "CRITICAL", "Critical", "Very Negative", "sec", "ESCALATED", "true", "AI_GENERATED", "Force a password reset, revoke active sessions, enable 2FA, and review account access logs."],
  ["Received a damaged product", "The product I received was damaged. The box was crushed and the item inside is broken.", "product", "Damaged Item", "MEDIUM", "Medium", "Negative", "ops", "ASSIGNED", "false", "AI_GENERATED", "Request photos of the damage, arrange a replacement or refund, and file a claim with the courier."],
  ["Refund has not been credited", "I returned the product two weeks ago but the refund has still not been credited to my account.", "payment", "Refund", "HIGH", "Medium", "Negative", "billing", "IN_PROGRESS", "false", "AI_GENERATED", "Check the return intake date, verify the refund initiation, and expedite the credit."],
  ["Unable to update my profile", "I keep getting an error when I try to save changes to my profile, so I cannot update my address.", "account", "Profile Update", "MEDIUM", "Low", "Neutral", "cs", "NEW", "false", "AI_GENERATED", "Reproduce the profile save flow, check validation rules, and fix the blocking error."],
  ["App crashes on checkout", "Every time I reach the checkout screen the mobile app crashes before I can complete payment.", "tech", "Mobile App", "HIGH", "High", "Negative", "ts", "IN_PROGRESS", "false", "AI_GENERATED", "Reproduce the checkout crash, inspect crash logs, and deploy a hotfix."],
  ["Wrong amount charged on invoice", "My latest invoice shows a charge that does not match my plan. It is higher than what I agreed to.", "billing", "Invoice Dispute", "HIGH", "Medium", "Negative", "billing", "ASSIGNED", "false", "AI_GENERATED", "Compare the invoice line items with the agreed plan and correct any discrepancy."],
  ["Network outage across the building", "The entire office network has been down for the last two hours and nobody can access any internal system.", "infra", "Outage", "CRITICAL", "Critical", "Very Negative", "ts", "ESCALATED", "false", "AI_GENERATED", "Escalate to the infrastructure team, check the core switch and uplink, and communicate status to affected users."],
  ["Offensive behaviour by support representative", "The support representative spoke to me rudely and ended the chat without resolving my issue.", "staff", "Staff Conduct", "MEDIUM", "Medium", "Very Negative", "cs", "NEW", "false", "AI_GENERATED", "Review the chat transcript, speak with the representative, and offer an apology to the customer."],
  ["Deactivated account without notice", "My account was deactivated without any email or explanation. I cannot login at all now.", "account", "Account Access", "CRITICAL", "High", "Very Negative", "cs", "IN_PROGRESS", "true", "HUMAN_CORRECTED", "Check for automated deactivation flags, restore access, and notify the customer of the reason."],
  ["Order cancelled but still charged", "My order was cancelled by the system but I was still charged for it. I want my money back.", "payment", "Refund", "HIGH", "Medium", "Very Negative", "billing", "IN_PROGRESS", "false", "AI_GENERATED", "Confirm the cancellation, reverse the hold, and issue a refund."],
  ["Slow internet in remote office", "The remote office internet is very slow and video conferencing keeps dropping during meetings.", "tech", "Internet Connectivity", "MEDIUM", "Medium", "Negative", "ts", "ASSIGNED", "false", "AI_GENERATED", "Check the remote link bandwidth and router and upgrade the connection if necessary."],
  ["Did not receive promotional discount", "The promotion code I was promised was not applied to my purchase and I was charged full price.", "billing", "Pricing", "LOW", "Low", "Neutral", "billing", "NEW", "false", "AI_GENERATED", "Verify the promotion eligibility and refund the difference."],
  ["Faulty laptop battery", "My laptop battery drains within 30 minutes even when fully charged. It is less than a year old.", "tech", "Hardware", "MEDIUM", "Medium", "Negative", "ts", "ASSIGNED", "false", "AI_GENERATED", "Diagnose the battery health and arrange a warranty replacement."],
  ["Received wrong item in my order", "I ordered a black model but received a silver one. The package contents are incorrect.", "delivery", "Wrong Item", "MEDIUM", "Medium", "Negative", "ops", "IN_PROGRESS", "false", "AI_GENERATED", "Confirm the ordered versus shipped item and arrange the correct item or a return."],
  ["CEO impersonation phishing email", "A phishing email pretending to be from our CEO is being sent to staff. It asks people to buy gift cards.", "security", "Phishing", "CRITICAL", "Critical", "Negative", "sec", "ESCALATED", "true", "HUMAN_CORRECTED", "Warn all staff, block the sender, and add the domain to the blocklist."],
  ["Subscription renewal failure", "My subscription renewed with an error and I was locked out of the premium features I paid for.", "payment", "Renewal", "HIGH", "Medium", "Negative", "billing", "IN_PROGRESS", "false", "AI_GENERATED", "Verify the renewal payment, restore premium access, and confirm the next renewal date."],
  ["App does not support dark mode", "The mobile app does not have a dark mode option, which makes it hard to use at night.", "tech", "Feature Request", "LOW", "Low", "Neutral", "ts", "NEW", "false", "AI_GENERATED", "Log the feature request and share the roadmap timeline with the customer."],
  ["Elevator out of service", "The office elevator has been out of service for three days, forcing staff to use the stairs.", "infra", "Facilities", "MEDIUM", "Medium", "Neutral", "ops", "ASSIGNED", "false", "AI_GENERATED", "Contact the maintenance contractor and provide an estimated repair date."],
  ["Multiple failed login attempts", "I keep seeing failed login attempts on my account from an unknown location. I am worried it will be hacked.", "security", "Suspicious Activity", "HIGH", "High", "Negative", "sec", "IN_PROGRESS", "false", "AI_GENERATED", "Freeze the account, reset credentials, and investigate the source of the attempts."],
  ["Late delivery of medical supplies", "Our urgent medical order was supposed to arrive yesterday but it is stuck in transit and patients are affected.", "delivery", "Urgent Delivery", "CRITICAL", "Critical", "Very Negative", "ops", "ESCALATED", "false", "AI_GENERATED", "Escalate to expedited delivery and provide a clear revised ETA."],
  ["Billing department unresponsive", "I have emailed the billing department 3 times about a refund and nobody has responded in over a week.", "staff", "Unresponsiveness", "HIGH", "Medium", "Very Negative", "cs", "NEW", "true", "AI_GENERATED", "Route to a supervisor, respond to the customer, and prioritise the pending refund."],
  ["Feature request: offline mode", "It would help a lot if the app had an offline mode so I can continue working without internet.", "tech", "Feature Request", "LOW", "Low", "Positive", "ts", "NEW", "false", "AI_GENERATED", "Add to the product backlog and acknowledge the request."],
  ["Cannot find my invoice PDF", "I need a copy of my last invoice for accounting but I cannot find it in the app.", "billing", "Document Access", "LOW", "Low", "Neutral", "billing", "NEW", "false", "AI_GENERATED", "Locate the invoice and provide a downloadable PDF."],
  ["Hot water not working in washroom", "The washroom on the ground floor has no hot water. It has been like this for a week.", "infra", "Facilities", "MEDIUM", "Low", "Neutral", "ops", "ASSIGNED", "false", "AI_GENERATED", "Raise a maintenance ticket with the plumbing contractor."],
  ["Friend's referral bonus not credited", "I referred a friend who signed up but I never received the referral bonus I was promised.", "account", "Promotion", "LOW", "Low", "Neutral", "cs", "NEW", "false", "AI_GENERATED", "Verify the referral was valid and credit the bonus."],
  ["Delay in ticket support response", "I opened a technical ticket 4 days ago and still have not received a response from the support team.", "staff", "Unresponsiveness", "MEDIUM", "Medium", "Negative", "cs", "ESCALATED", "false", "AI_GENERATED", "Assign the ticket to an available agent and provide an update to the customer."],
  ["Cannot upload a document to my profile", "Every time I try to upload my ID document for verification it fails with a generic error.", "account", "Verification", "MEDIUM", "Medium", "Neutral", "cs", "IN_PROGRESS", "false", "AI_GENERATED", "Test the upload flow and fix the file size or format validation."],
  ["Charged for a free trial", "I signed up for a free trial but I was charged on the first day instead of at the end of the trial.", "billing", "Billing Error", "HIGH", "Medium", "Very Negative", "billing", "IN_PROGRESS", "false", "AI_GENERATED", "Check the trial configuration and reverse the erroneous charge."],
  ["WiFi drops on the third floor", "The WiFi keeps dropping on the third floor conference rooms making it impossible to hold calls.", "tech", "Internet Connectivity", "MEDIUM", "Medium", "Negative", "ts", "ASSIGNED", "false", "AI_GENERATED", "Check access point coverage on the third floor and adjust placement."],
  ["Change of address not reflected", "I moved last month and updated my address, but my bills are still being sent to the old address.", "account", "Profile Update", "MEDIUM", "Low", "Neutral", "cs", "NEW", "false", "AI_GENERATED", "Confirm the new address is saved on all systems and update billing details."],
  ["App logs out after every restart", "I have to login again every time I restart my phone. My session never stays logged in.", "tech", "Mobile App", "MEDIUM", "Medium", "Negative", "ts", "ASSIGNED", "false", "AI_GENERATED", "Investigate the token refresh flow and fix session persistence."],
  ["Payout notification not received", "I did not receive the payout notification this month even though others did. I want to check my account.", "service", "Notification Issue", "MEDIUM", "Low", "Neutral", "cs", "NEW", "true", "HUMAN_CORRECTED", "Check notification preferences and re-send the payout notice."],
  ["Report a data privacy concern", "I am concerned that my personal data may have been shared without my consent after a recent support call.", "security", "Privacy", "HIGH", "High", "Very Negative", "sec", "IN_PROGRESS", "false", "AI_GENERATED", "Review data access logs and initiate a privacy review."],
  ["Request to close duplicate account", "I accidentally created two accounts. I would like to close the duplicate one and merge my data.", "account", "Account Merge", "LOW", "Low", "Neutral", "cs", "NEW", "false", "AI_GENERATED", "Verify both accounts belong to the customer and merge or close as requested."],
  ["Printer not printing in Finance", "The printer in the Finance department is not printing and shows an offline error.", "tech", "Printer", "MEDIUM", "Low", "Neutral", "ts", "ASSIGNED", "false", "AI_GENERATED", "Check the printer connection and clear the offline state."],
  ["Very long wait on support call", "I waited 35 minutes on hold to talk to support, which is unacceptable for an urgent billing issue.", "staff", "Service Quality", "HIGH", "Medium", "Very Negative", "cs", "NEW", "false", "AI_GENERATED", "Review staffing and queue routing to reduce hold times."],
  ["Order marked delivered but not received", "My package was marked as delivered but I never received it. The delivery photo shows the wrong door.", "delivery", "Delivery Dispute", "HIGH", "High", "Very Negative", "ops", "ESCALATED", "false", "AI_GENERATED", "Open a carrier investigation and arrange a re-delivery or refund."],
  ["Auto-payment charged before due date", "My auto-payment was charged 2 days before the due date leaving my account short.", "billing", "Billing Error", "MEDIUM", "Medium", "Negative", "billing", "IN_PROGRESS", "false", "AI_GENERATED", "Check the payment schedule and correct the charge date."],
  ["Missing feature in admin console", "The admin console does not have a bulk export option which makes monthly reporting very slow.", "tech", "Feature Request", "LOW", "Low", "Neutral", "ts", "NEW", "true", "HUMAN_CORRECTED", "Add the bulk export feature to the product backlog and share the planned timeline."],
  ["Suspicious charge on my statement", "I found a small charge on my card that I do not recognise. I want to confirm it is not fraudulent.", "security", "Fraud", "HIGH", "High", "Very Negative", "sec", "IN_PROGRESS", "false", "AI_GENERATED", "Verify the transaction details and investigate whether it is fraudulent."],
  ["Cannot change my email address", "The app will not let me change the email address on my account. It says the field is locked.", "account", "Account Access", "MEDIUM", "Low", "Neutral", "cs", "NEW", "false", "AI_GENERATED", "Verify the customer and unlock the email change flow."],
  ["Request refund for cancelled service", "I cancelled my service but I was still charged for the next month. I need a refund for the unused period.", "payment", "Refund", "HIGH", "Medium", "Negative", "billing", "IN_PROGRESS", "false", "AI_GENERATED", "Confirm the cancellation date and refund the unused period."],
  ["Training session didn't start on time", "The training session started 20 minutes late with poor audio quality, which impacted the attendees.", "staff", "Service Quality", "LOW", "Low", "Neutral", "cs", "NEW", "false", "HUMAN_CORRECTED", "Review the event logistics and coordinate with the presenter."],
  ["Unable to scan QR code in app", "The QR code in the app will not scan at the entry gate, preventing me from entering the building.", "tech", "Mobile App", "HIGH", "Medium", "Negative", "ts", "ASSIGNED", "false", "AI_GENERATED", "Fix the QR generation and confirm the device display settings."],
  ["Duplicate report entries in my account", "I see the same report several times listed in my account. It looks like a display bug.", "tech", "Software Bug", "LOW", "Low", "Neutral", "ts", "NEW", "false", "AI_GENERATED", "Investigate the duplicate entries and clean the account data."],
  ["Refund still not received after 3 weeks", "It has been 3 weeks since my return was accepted and I still have not received my refund.", "payment", "Refund", "HIGH", "High", "Very Negative", "billing", "ESCALATED", "false", "AI_GENERATED", "Trace the refund through the payment provider and escalate if needed."],
  ["Account locked after password change", "I changed my password successfully but now my account is locked and I cannot login.", "account", "Account Access", "HIGH", "High", "Negative", "cs", "IN_PROGRESS", "false", "AI_GENERATED", "Unlock the account and confirm the password change is saved."],
  ["Employee badge not working", "My office badge stops working at the main entrance every few days and I have to ask security to let me in.", "infra", "Access Control", "MEDIUM", "Low", "Neutral", "ops", "ASSIGNED", "false", "AI_GENERATED", "Re-program the badge and check the door controller logs."],
  ["Request information about my spending", "I want a breakdown of my spending for the last six months for my personal records.", "billing", "Statement Request", "LOW", "Low", "Positive", "billing", "NEW", "false", "AI_GENERATED", "Generate and share the spending statement."],
  ["Received spam notifications in app", "I have been receiving spam-like notifications in the app promoting offers I did not opt into.", "service", "Notifications", "LOW", "Low", "Negative", "cs", "NEW", "false", "AI_GENERATED", "Check notification opt-in settings and stop unsolicited messages."],
  ["Issues with conference room booking", "The conference room booking system is double-booking rooms and showing rooms as free when they are occupied.", "tech", "Software Bug", "MEDIUM", "Medium", "Negative", "ts", "ASSIGNED", "false", "AI_GENERATED", "Fix the booking conflict logic and audit recent bookings."],
  ["Help understanding my usage bill", "I do not understand some of the line items on my usage bill and I want an explanation.", "billing", "Invoice Dispute", "LOW", "Low", "Neutral", "billing", "NEW", "false", "AI_GENERATED", "Explain each line item and clarify the charges."],
];

/** Deterministic PRNG so demo data stays stable across runs. */
export function mulberry32(a: number) {
  return function () {
    a |= 0; a = (a + 0x6D2B79F) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ 0;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export const UUID = (n: number) =>
  `00000000-0000-4000-8000-${String(n).padStart(12, "0")}`;

export const DEPT_IDS: Record<string, string> = {
  cs: UUID(11), ts: UUID(12), billing: UUID(13), ops: UUID(14), sec: UUID(15),
};

export const CAT_IDS: Record<string, string> = {
  tech: UUID(21), billing: UUID(22), payment: UUID(23), account: UUID(24), delivery: UUID(25),
  product: UUID(26), service: UUID(27), security: UUID(28), infra: UUID(29), staff: UUID(30), other: UUID(31),
};

export const USER_IDS = {
  admin: UUID(1), manager: UUID(2), agentTech: UUID(3), agentBilling: UUID(4), agentCs: UUID(5),
  agentOps: UUID(6), agentSec: UUID(7), c1: UUID(8), c2: UUID(9), c3: UUID(10),
  c4: UUID(41), c5: UUID(42), c6: UUID(43), c7: UUID(44), c8: UUID(45),
  c9: UUID(46), c10: UUID(47),
};

export const DEPT_NAME: Record<string, string> = {
  cs: "Customer Support", ts: "Technical Support", billing: "Billing & Finance", ops: "Operations", sec: "Security",
};

